W_CUSTOMERS = ["HAOS", "HMB", "HMMA", "HMMC", "HMMR", "KAGA", "KASK", "KMX", "KIN", "HMMI"]
W_OVS_INVALID_TYPE = ["INFORMATION"]
# W_OVS_INVALID_TYPE = ["INFORMATION", "PILOT"]
INVALID_PPR_SUPPLIED_FROM = ["글로비스 인도(N)", "글로비스 인도(A)"]

REPROCESS = False
RELOAD_CHARTS = True

PRE_NOTI = True
MONDAY_TO_SATURDAY = False
REGULAR_MONTH = False
YYYYMM = None
WEEKLY_CUSTOMER = True
WEEKLY_TYPE = True
N_WEEKS = None
N_RANKS = 3